# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: python:3.6-alpine
        environment:
        FLASK_APP: $FLASK_APP
        FLASK_CONFIG: $FLASK_CONFIG
      #  SECRET_KEY: 3128b4588e7f4305b5501025c13ceca5
      #  FLASK_CONFIG: testing
      #- image: mysql/mysql-server:5.7
      #  environment: 
      #  MYSQL_RANDOM_ROOT_PASSWORD: yes
      #  MYSQL_DATABASE: flasky
      #  MYSQL_USER: flasky
      #  MYSQL_PASSWORD: p@ssw0rd 
      
    working_directory: ~/repo

    steps:
      - checkout
      - run: mkdir test-reports
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements/docker.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python -m venv venv
            venv/bin/pip install -r requirements/docker.txt
      - run:
          name: deploy 
          command: |
            source venv/bin/activate
            export FLASK_APP=flasky.py
            while true; do
              flask deploy
              if [[ "$?" == "0" ]]; then
                break
              fi
              echo Deploy command failed, retrying in 5 secs...
              sleep 5
            done
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements/docker.txt" }}

      - run:
          name: run tests
          command: |
            source venv/bin/activate
      #      export FLASK_APP=flasky.py
            flask test --coverage

      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/
          