apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: flasky-deployment
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 3
  template:
    metadata:
      labels:
        app: flasky
    spec:
      containers:
      - name: flasky
        image: eu.gcr.io/dp-flaskyapp/flasky:1.0
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: secret-volume
          mountPath: /secret-volume
          readOnly: true
        env:
          - name: MAIL_USERNAME
            valueFrom:
              secretKeyRef:
                name: email-secrets
                key: username
          - name: MAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: email-secrets
                key: password
      volumes:
      - name: secret-volume
        secret: 
          secretName: email-secrets
        